### ISSUE TITLE
um

### ISSUE THREAD

**Issue by Zapcrash** [jw2417/eft-chams#2]
I was trying for a while to make it work but I couldn't, it's probably because of the size of the file I think

**Comment by jw2417** [comment]
its an older version for eft

**Comment by Zapcrash** [comment]
Do you have any source where you got this to look for it and try to update it?
I have made chams with another source but it is external replacing the textures and it does not have vischeck or full body, I want to try to do something like what you showed.

**Comment by jw2417** [comment]
not for you

**Comment by Zapcrash** [comment]
ok, thanks anyway for the quick response
